server:
  port: 8888
spring:
  application:
    name: learn-config
  cloud:
     config:
      server:
        git:
          uri: https://github.com/shanks-devil/config-repo.git
          basedir: /Users/CN40312/config-repo
          clone-on-start: true